#!/bin/sh
PIDFILE="/var/run/rtsp-server.pid"

status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    kill -0 "$pid" >/dev/null && echo "PID: $pid" || return 1
  fi
}

start()
{
  LOG=/dev/null
  echo "Starting RTSP server..."
  #snx_rtsp_server -W 1920 -H 1080 -Q 10 -b 4096 -a >$LOG 2>&1 &
  #snx_snapshot -m -q 10 -n 1 -W 1920 -H 1080 > $LOG 2>&1 &
  snx_snapshot_v3 -m -q 40 -n 1 -T 320 -W 1920 -H 1080 -N salon -Y 5 -f 4 -t "mqtt_send_picture.sh /tmp/www/snapshot.jpg" -l "mqtt_alarm.sh ON" -b "mqtt_alarm.sh WARN" -c "mqtt_alarm.sh OFF" >$LOG 2>&1 &
  echo "$!" > "$PIDFILE"
}

stop()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
     kill $pid ||  rm "$PIDFILE"
  fi
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi

